# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b92665024e589968e5adc7bb0d45a69d29781fa9626629f67802d87dfb9250243853bf481ecb1bfa58cb0d8b9d23d227a251af88a388a353274d0720eda1c384

test:
  secret_key_base: 9fd030d97799e1766147386fdbab883c8ee370245b70e28e08c458fdf8a78102abe6bf879b9bc56a11baf0c716e9d63aa2de9b1c95688a5ca8fa21e1b1ea0a9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
